### ISSUE TITLE
Defined GPIO behavior during boot

### ISSUE THREAD

**Issue by BrotKolben** [siemens/meta-iot2050#166] opened 2021-09-01 11:59 UTC
While booting up the IOT2050, configured digital outputs might "flicker" between LOW and HIGH, and not show a defined state. Configuration in iot2050setup does not prevent this from happening: 
![image](https://user-images.githubusercontent.com/37112710/131666733-aa6b8654-d0e2-44ab-b950-efe505c533a8.png)
The flickering occurs up-until the device is fully booted up. 
Having a default LOW state during boot would be a desired requirement from safety perspective.

**Comment by jan-kiszka** [comment] 2021-09-01 12:03
I think we discussed this somewhere already: Without consistent changes across the device trees (firmware and kernel), the safe state of GPIOs is "input" (high impedance). I think this is what we have today.

**Comment by jan-kiszka** [comment] 2021-09-13 11:04
In fact, that may even be unsolvable via firmware patches, because before the firmware comes power-on, and that defines the GPIO mode in hardware, not by any software bit. @BaochengSu, am I right?

**Comment by BaochengSu** [comment] 2021-09-13 11:38
@jan-kiszka I think so, the GPIO pin has a initail mode before change it in the spl, that initail mode could not be configure to output low or high, even could not be a GPIO at all.

Anyway, I am contacting with TI regarding this topic.

**Comment by BaochengSu** [comment] 2021-09-13 12:09
Checked w/ TI, confirmed that our understand is correct.

**Comment by jan-kiszka** [comment] 2021-10-18 05:18
Let's close this as "not possible", unfortunately.

**Closed by jan-kiszka** 2021-10-18 05:18 UTC
